### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focusScope' of undefined

### ISSUE THREAD

**Issue by PranavOFS** [angular-ui/AngularJS-Atom#40]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [angularjs](https://github.com/angular-ui/AngularJS-Atom) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'focusScope' of undefined

```
At /c:/Users/pk/.atom/packages/scope-inspector/lib/scope-path-view.coffee:89

TypeError: Cannot read property 'focusScope' of undefined
  at ScopePathView.module.exports.ScopePathView.onLeaveButton (C:\Users\pranav.OFS1\.atom\packages\scope-inspector\lib\scope-path-view.coffee:47:29)
  at HTMLDivElement.handler (D:\tools\atom\app-0.201.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (D:\tools\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (D:\tools\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
block-travel, v1.0.2
column-select, v0.2.0
hex, v0.5.0
highlight-selected, v0.9.1
js-refactor, v0.3.0
linter, v0.12.6
linter-csslint, v0.0.13
linter-gjslint, v0.0.5
linter-jshint, v0.1.5
linter-jsonlint, v0.1.4
linter-less, v0.4.0
linter-scss-lint, v1.0.4
neon-selection, v0.3.2
open-recent, v2.2.2
project-colorize, v0.2.0
quick-jump, v0.0.4
refactor, v0.4.1
regex-railroad-diagram, v0.7.1
scope-inspector, v0.2.1
word-jumper, v0.2.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by outsideris** [comment]
I can't reproduce it. Could you please provide more detail about your situation?
